[theme]
primaryColor = "#FF00FF"          # Lisa Frank Magenta
backgroundColor = "#FFFFFF"       # Clean white base to make neons pop
secondaryBackgroundColor = "#6EF7F7" # Electric Cyan for sidebar
textColor = "#ac3cfe"             # Deep Purple for text
font = "sans serif"
